"use client";

import Link from "next/link";
import { useI18n } from "@/i18n/context";
import { useAuth } from "./providers";
import { useLoginGate } from "@/hooks/useLoginGate";
import { LocaleSwitcher } from "@/components/dashboard/LocaleSwitcher";

const icons = {
  shield: <svg className="w-7 h-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
  chart: <svg className="w-7 h-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M3 3v18h18"/><path d="M7 16l4-8 4 4 5-9"/></svg>,
  brain: <svg className="w-7 h-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="12" cy="12" r="3"/><path d="M12 2a7 7 0 017 7c0 2.38-1.19 4.47-3 5.74V17a2 2 0 01-2 2h-4a2 2 0 01-2-2v-2.26C6.19 13.47 5 11.38 5 9a7 7 0 017-7z"/></svg>,
  bell: <svg className="w-7 h-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M18 8A6 6 0 006 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 01-3.46 0"/></svg>,
  calc: <svg className="w-7 h-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="4" y="2" width="16" height="20" rx="2"/><path d="M8 6h8M8 10h8M8 14h3M8 18h3M15 14h1M15 18h1"/></svg>,
  report: <svg className="w-7 h-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="8" y1="13" x2="16" y2="13"/><line x1="8" y1="17" x2="16" y2="17"/></svg>,
};

const features = {
  en: [
    { icon: icons.shield, title: "Real-time Compliance", desc: "Monitor daily loss, max drawdown, and position limits against your Prop Firm's rules. 4-level alerts: SAFE → WARNING → CRITICAL → DANGER." },
    { icon: icons.chart, title: "Live K-Line Charts", desc: "Real market data from OKX and TwelveData. BTC, ETH, EUR/USD, XAU/USD with MA, BOLL, MACD, RSI indicators." },
    { icon: icons.brain, title: "AI Signal Scoring", desc: "Paste any trading signal and get a Claude AI score (0-100) with risk assessment. Filter noise, find the signal worth acting on." },
    { icon: icons.bell, title: "Telegram Alerts", desc: "Get instant Telegram notifications when approaching compliance limits. Never miss a critical risk warning." },
    { icon: icons.calc, title: "Position Calculator", desc: "1% risk rule with Kelly criterion reference. Know exactly how much to trade based on your account state." },
    { icon: icons.report, title: "AI Briefing", desc: "Pre-market AI analysis: risk status, today's focus, and actionable recommendation generated by Claude." },
  ],
  zh: [
    { icon: icons.shield, title: "实时合规监控", desc: "监控每日亏损、最大回撤和仓位限制，对照你的 Prop Firm 考核规则。4 级告警：SAFE → WARNING → CRITICAL → DANGER。" },
    { icon: icons.chart, title: "实时 K 线图表", desc: "来自 OKX 和 TwelveData 的真实行情数据。BTC、ETH、EUR/USD、XAU/USD，支持 MA、BOLL、MACD、RSI 指标。" },
    { icon: icons.brain, title: "AI 信号评分", desc: "粘贴任何交易信号，Claude AI 给出 0-100 评分和风险评估。从噪音中过滤出值得行动的信号。" },
    { icon: icons.bell, title: "Telegram 告警", desc: "接近合规限额时即时推送 Telegram 通知。不错过任何关键风险预警。" },
    { icon: icons.calc, title: "仓位计算器", desc: "1% 风险规则 + Kelly 比例参考。根据账户状态精确计算交易手数。" },
    { icon: icons.report, title: "AI 盘前简报", desc: "盘前 AI 分析：风险状态、今日关注、可操作建议，由 Claude 生成。" },
  ],
};

const firms = [
  { name: "FTMO", market: "FX / Indices / Commodities / Crypto", dd: "10% static" },
  { name: "TopStep", market: "Futures", dd: "Trailing EOD" },
  { name: "CryptoFundTrader", market: "Crypto / FX", dd: "10% static" },
  { name: "FundedNext", market: "FX / Indices / Commodities / Crypto", dd: "10% static" },
  { name: "The5ers", market: "FX / Indices / Commodities", dd: "6% Stop Out" },
  { name: "Apex", market: "Futures", dd: "Live trailing" },
  { name: "Maven", market: "FX / Indices / Commodities / Crypto", dd: "8% static" },
  { name: "FundingPips", market: "FX / Indices / Commodities / Crypto", dd: "10% (2-step) / 6% (1-step)" },
];

const texts = {
  en: {
    hero: "Don't help you trade. Just help you not get eliminated.",
    heroSub: "AI-powered risk management for Prop Firm traders. Real-time compliance monitoring, intelligent signal filtering, position sizing — all in one dashboard.",
    cta: "Try for free — no signup required",
    login: "Sign In",
    dashboard: "Go to Dashboard",
    featuresTitle: "Everything you need to pass the challenge",
    firmsTitle: "Supported Prop Firms",
    firmMore: "More firms coming soon...",
    pricingTitle: "Pricing",
    free: "Free",
    freeFeatures: ["1 Prop Firm account", "3 signal sources", "Basic compliance checks", "Web alerts"],
    proFeatures: ["3 accounts", "Unlimited signals", "AI signal scoring", "AI briefing", "Telegram alerts"],
    premiumFeatures: ["Unlimited accounts", "Position calculator", "Historical analysis", "All alert channels"],
    ctaBottom: "Start monitoring your Prop Firm challenge now",
    ctaBottomSub: "Free to start. No credit card required.",
  },
  zh: {
    hero: "不帮你交易，只帮你不被淘汰。",
    heroSub: "Prop Firm 交易者的 AI 风控管家。实时合规监控、智能信号过滤、仓位计算 —— 一个 Dashboard 搞定。",
    cta: "免费试用，无需注册",
    login: "登录",
    dashboard: "进入 Dashboard",
    featuresTitle: "通过挑战所需的一切",
    firmsTitle: "支持的 Prop Firm",
    firmMore: "更多 Prop Firm 即将支持...",
    pricingTitle: "定价",
    free: "免费",
    freeFeatures: ["1 个 Prop Firm 账户", "3 个信号源", "基础合规检查", "Web 告警"],
    proFeatures: ["3 个账户", "无限信号源", "AI 信号评分", "AI 盘前简报", "Telegram 告警"],
    premiumFeatures: ["无限账户", "仓位计算器", "历史分析", "全渠道告警"],
    ctaBottom: "现在开始监控你的 Prop Firm 挑战",
    ctaBottomSub: "免费使用，无需信用卡。",
  },
};

export default function HomePage() {
  const { locale } = useI18n();
  const { user } = useAuth();
  const { openGate } = useLoginGate();
  const t = texts[locale] || texts.en;
  const f = features[locale] || features.en;

  return (
    <main className="min-h-screen">
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-zinc-950/80 backdrop-blur-lg border-b border-zinc-800/50">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <span className="text-white font-bold text-lg">PropGuard AI</span>
          <div className="flex items-center gap-4">
            <LocaleSwitcher />
            {user ? (
              <Link href="/dashboard" className="px-4 py-2 bg-white text-black text-sm font-medium rounded-lg hover:bg-zinc-200 transition-colors">
                {t.dashboard}
              </Link>
            ) : (
              <>
                <button onClick={() => openGate(t.login)} className="text-sm text-zinc-400 hover:text-white transition-colors">
                  {t.login}
                </button>
                <button onClick={() => openGate(t.login)} className="px-4 py-2 bg-white text-black text-sm font-medium rounded-lg hover:bg-zinc-200 transition-colors">
                  {t.cta}
                </button>
              </>
            )}
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-4xl mx-auto text-center space-y-6">
          <h1 className="text-4xl md:text-6xl font-bold text-white leading-tight">
            {t.hero}
          </h1>
          <p className="text-lg md:text-xl text-zinc-400 max-w-2xl mx-auto leading-relaxed">
            {t.heroSub}
          </p>
          <div className="flex gap-4 justify-center pt-4">
            <Link href="/dashboard" className="px-8 py-3 bg-white text-black font-medium rounded-lg hover:bg-zinc-200 transition-colors text-lg">
              {t.cta}
            </Link>
            <Link href="/docs" className="px-8 py-3 border border-zinc-700 text-zinc-300 font-medium rounded-lg hover:border-zinc-500 hover:text-white transition-colors text-lg">
              Docs
            </Link>
          </div>
          <div className="flex gap-3 justify-center pt-2">
            <span className="px-3 py-1 bg-green-900/30 text-green-400 text-xs rounded-full">Read-only</span>
            <span className="px-3 py-1 bg-blue-900/30 text-blue-400 text-xs rounded-full">AI Powered</span>
            <span className="px-3 py-1 bg-purple-900/30 text-purple-400 text-xs rounded-full">Zero Legal Risk</span>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 px-6 border-t border-zinc-800/50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-white text-center mb-12">{t.featuresTitle}</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {f.map((feat, i) => (
              <div key={i} className="bg-zinc-900/50 border border-zinc-800/50 rounded-xl p-6 space-y-3 hover:border-zinc-700 transition-colors">
                <div className="text-green-400">{feat.icon}</div>
                <h3 className="text-lg font-semibold text-white">{feat.title}</h3>
                <p className="text-sm text-zinc-400 leading-relaxed">{feat.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Supported Firms */}
      <section className="py-20 px-6 border-t border-zinc-800/50">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-white text-center mb-12">{t.firmsTitle}</h2>
          <div className="grid md:grid-cols-3 gap-6">
            {firms.map((firm) => (
              <div key={firm.name} className="bg-zinc-900/50 border border-zinc-800/50 rounded-xl p-6 text-center space-y-2">
                <h3 className="text-xl font-bold text-white">{firm.name}</h3>
                <p className="text-sm text-zinc-400">{firm.market}</p>
                <p className="text-xs text-zinc-500">Max DD: {firm.dd}</p>
              </div>
            ))}
          </div>
          <p className="text-center text-zinc-600 text-sm mt-6">{t.firmMore}</p>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-20 px-6 border-t border-zinc-800/50">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-white text-center mb-12">{t.pricingTitle}</h2>
          <div className="grid md:grid-cols-3 gap-6">
            <PricingCard tier={t.free} price="$0" features={t.freeFeatures} />
            <PricingCard tier="Pro" price="$29/mo" features={t.proFeatures} highlight />
            <PricingCard tier="Premium" price="$49/mo" features={t.premiumFeatures} />
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6 border-t border-zinc-800/50">
        <div className="max-w-2xl mx-auto text-center space-y-4">
          <h2 className="text-3xl font-bold text-white">{t.ctaBottom}</h2>
          <p className="text-zinc-400">{t.ctaBottomSub}</p>
          <Link href="/dashboard" className="inline-block px-8 py-3 bg-white text-black font-medium rounded-lg hover:bg-zinc-200 transition-colors text-lg mt-4">
            {t.cta}
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-zinc-800/50 py-8 px-6">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-zinc-600">
          <span>PropGuard AI v0.1.0</span>
          <div className="flex gap-6">
            <Link href="/docs" className="hover:text-white transition-colors">Docs</Link>
            <a href="https://t.me/PropGuardAIBot" className="hover:text-white transition-colors">Telegram Bot</a>
            <a href="https://github.com/StrangeXin/propguard-ai" className="hover:text-white transition-colors">GitHub</a>
          </div>
        </div>
      </footer>
    </main>
  );
}

function PricingCard({ tier, price, features, highlight = false }: { tier: string; price: string; features: string[]; highlight?: boolean }) {
  const { openGate } = useLoginGate();
  return (
    <div className={`rounded-xl p-6 space-y-4 ${highlight ? "bg-zinc-800 ring-1 ring-green-800" : "bg-zinc-900/50 border border-zinc-800/50"}`}>
      <div>
        <p className="text-sm text-zinc-400">{tier}</p>
        <p className="text-3xl font-bold text-white">{price}</p>
      </div>
      <ul className="space-y-2">
        {features.map((f, i) => (
          <li key={i} className="text-sm text-zinc-300 flex items-start gap-2">
            <span className="text-green-500 mt-0.5">&#10003;</span>
            {f}
          </li>
        ))}
      </ul>
      <button onClick={() => openGate("Get Started")} className={`block w-full text-center py-2 rounded-lg text-sm font-medium transition-colors ${highlight ? "bg-white text-black hover:bg-zinc-200" : "bg-zinc-800 text-zinc-300 hover:bg-zinc-700"}`}>
        Get Started
      </button>
    </div>
  );
}
